https://онлайн-читать.рф – request error: Failed to parse: https://онлайн-читать.рф
https://irr.ru – request error: HTTPSConnectionPool(host='irr.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105911cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://beru.ru tiu.ru – request error: HTTPSConnectionPool(host='beru.ru%20tiu.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1066e9d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://rulit.online – request error: HTTPSConnectionPool(host='rulit.online', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106011130>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://roszdravnadzor.rufuturerussia.gov.ru – request error: HTTPSConnectionPool(host='roszdravnadzor.rufuturerussia.gov.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1112b1310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://kodeks.rusudact.ru – request error: HTTPSConnectionPool(host='kodeks.rusudact.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106cc5fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://russia.tv free.tnt-online.ru – request error: HTTPSConnectionPool(host='russia.tv%20free.tnt-online.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x101b55370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://онлайнинспекция.рф – request error: Failed to parse: https://онлайнинспекция.рф
https://money.yandex.ru – request error: HTTPSConnectionPool(host='money.yandex.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105b11160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
