https://mirconnect.ru – request error: HTTPSConnectionPool(host='mirconnect.ru', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x107f0bcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
https://lentainform.com – request error: HTTPSConnectionPool(host='lentainform.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104a8bcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
